import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
import json
import config

KPI_METADATA = {
    'grid_consumption': {
        'title': 'Grid Consumption',
        'description': 'Electricity consumed from the grid by each building over time (in kWh). Negative values indicate electricity exported to the grid.'
    },
    'total_grid_consumption': {
        'title': 'Total Grid Consumption',
        'description': 'Total electricity consumed from the grid by all buildings combined (in kWh).'
    },
    'load': {
        'title': 'Building Load',
        'description': 'Non-shiftable electrical load for each building (in kWh).'
    },
    'total_load': {
        'title': 'Total Building Load',
        'description': 'Total non-shiftable electrical load for all buildings combined (in kWh).'
    },
    'cost': {
        'title': 'Electricity Cost',
        'description': 'The cost of electricity for each building, calculated from grid consumption and electricity price (in $).'
    },
    'total_cost': {
        'title': 'Total Electricity Cost',
        'description': 'The total cost of electricity for all buildings combined (in $).'
    },
    'pv_generation': {
        'title': 'PV Generation',
        'description': 'Electricity generated by photovoltaic (PV) panels for each building (in kWh).'
    },
    'total_pv_generation': {
        'title': 'Total PV Generation',
        'description': 'Total electricity generated by photovoltaic (PV) panels for all buildings combined (in kWh).'
    },
    'electrical_storage_soc': {
        'title': 'Electrical Storage SoC',
        'description': 'State of Charge (SoC) of the electrical storage (battery) for each building (as a percentage).'
    },
    'total_electrical_storage_soc': {
        'title': 'Total Electrical Storage SoC',
        'description': 'This plot is not particularly meaningful as it sums the SoC percentages of different batteries.'
    },
    'electrical_storage_action': {
        'title': 'Electrical Storage Action',
        'description': 'Action taken by the agent for the electrical storage of each building. Positive values indicate charging, negative values indicate discharging.'
    },
    'total_electrical_storage_action': {
        'title': 'Total Electrical Storage Action',
        'description': 'Sum of all electrical storage actions across all buildings.'
    },
    'summary_kpis': {
        'title': 'Summary KPIs',
        'description': 'A summary of key performance indicators for the entire simulation run.'
    }
}

def generate_available_data():
    """
    Scans for simulation runs and generates a JSON file with the available runs and KPIs.
    """
    kpi_base_dir = Path(config.KPI_OUTPUT_DIR)
    output_data_file = Path('gui/available_data.json')
    output_data_file.parent.mkdir(exist_ok=True)

    available_runs = []
    available_kpis = {}

    if not kpi_base_dir.exists():
        print(f"KPI directory not found: {kpi_base_dir}")
        return

    for run_dir in kpi_base_dir.iterdir():
        if run_dir.is_dir():
            run_id = run_dir.name
            available_runs.append(run_id)
            available_kpis[run_id] = []

            for kpi_file in run_dir.glob("*.csv"):
                file_name = kpi_file.stem
                metadata = KPI_METADATA.get(file_name, {'title': file_name.replace("_", " ").title()})
                title = metadata['title']
                available_kpis[run_id].append({'name': title, 'path': file_name})

    output_data = {
        'runs': sorted(available_runs, reverse=True),
        'kpis': available_kpis
    }

    with open(output_data_file, 'w') as f:
        json.dump(output_data, f, indent=4)

    print(f"\nAvailable data generated successfully in {output_data_file}")

if __name__ == '__main__':
    generate_available_data()