import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
import json
import config

KPI_METADATA = {
    'net_energy_exchange': {
        'title': 'Net Energy Exchange (Per Building)',
        'description': 'Net electricity exchange with the grid for each building (in kWh). Positive values are imports, negative values are exports.',
        'unit': 'kWh'
    },
    'total_net_energy_exchange': {
        'title': 'Total Net Energy Exchange',
        'description': 'Total net electricity exchange with the grid for all buildings combined (in kWh).',
        'unit': 'kWh'
    },
    'load': {
        'title': 'Building Load (Per Building)',
        'description': 'Non-shiftable electrical load + battery charging for each building (in kWh).',
        'unit': 'kWh'
    },
    'total_load': {
        'title': 'Total Building Load',
        'description': 'Total non-shiftable electrical load + battery charging for all buildings combined (in kWh).',
        'unit': 'kWh'
    },
    'non_shiftable_load': {
        'title': 'Building Non-shiftable Load (Per Building)',
        'description': 'Non-shiftable electrical load for each building (in kWh).',
        'unit': 'kWh'
    },
    'total_non_shiftable_load': {
        'title': 'Total Building Non-shiftable Load',
        'description': 'Total non-shiftable electrical load for all buildings combined (in kWh).',
        'unit': 'kWh'
    },
    'cost': {
        'title': 'Electricity Cost (Per Building)',
        'description': 'The cost of electricity for each building, calculated from grid consumption and electricity price (in $).',
        'unit': '$'
    },
    'total_cost': {
        'title': 'Total Electricity Cost',
        'description': 'The total cost of electricity for all buildings combined (in $).',
        'unit': '$'
    },
    'pv_generation': {
        'title': 'PV Generation (Per Building)',
        'description': 'Electricity generated by photovoltaic (PV) panels for each building (in kWh).',
        'unit': 'kWh'
    },
    'total_pv_generation': {
        'title': 'Total PV Generation',
        'description': 'Total electricity generated by photovoltaic (PV) panels for all buildings combined (in kWh).',
        'unit': 'kWh'
    },
    'electrical_storage_soc': {
        'title': 'Electrical Storage SoC (Per Building)',
        'description': 'State of Charge (SoC) of the electrical storage (battery) for each building.',
        'unit': '%'
    },
    'total_electrical_storage_soc': {
        'title': 'Total Electrical Storage SoC',
        'description': 'This plot is not particularly meaningful as it sums the SoC percentages of different batteries.',
        'unit': '%'
    },
    'electrical_storage_action': {
        'title': 'Electrical Storage Action (Per Building)',
        'description': 'Action taken by the agent for the electrical storage of each building. Positive values indicate charging, negative values indicate discharging.',
        'unit': 'Action'
    },
    'total_electrical_storage_action': {
        'title': 'Total Electrical Storage Action',
        'description': 'Sum of all electrical storage actions across all buildings.',
        'unit': 'Action'
    },
    'battery_discharge': {
        'title': 'Battery Discharge (Per Building)',
        'description': 'The rate of battery discharge for each building.',
        'unit': 'kW'
    },
    'total_battery_discharge': {
        'title': 'Total Battery Discharge',
        'description': 'The total rate of battery discharge for all buildings.',
        'unit': 'kW'
    },
    'energy_export': {
        'title': 'Energy Export (Per Building)',
        'description': 'Energy exported to the grid by each building.',
        'unit': 'kWh'
    },
    'total_energy_export': {
        'title': 'Total Energy Export',
        'description': 'Total energy exported to the grid by all buildings.',
        'unit': 'kWh'
    },
    'energy_imported': {
        'title': 'Energy Imported from Grid (Per Building)',
        'description': 'Energy imported from the grid by each building.',
        'unit': 'kWh'
    },
    'total_energy_imported': {
        'title': 'Total Energy Imported from Grid',
        'description': 'Total energy imported from the grid by all buildings.',
        'unit': 'kWh'
    },
    'summary_kpis': {
        'title': 'Summary KPIs',
        'description': 'A summary of key performance indicators for the entire simulation run.',
        'unit': ''
    }
}

def generate_available_data():
    """
    Scans for simulation runs and generates a JSON file with the available runs and KPIs.
    """
    kpi_base_dir = Path(config.KPI_OUTPUT_DIR)
    output_data_file = Path('gui/available_data.json')
    output_data_file.parent.mkdir(exist_ok=True)

    available_runs = []
    available_kpis = {}

    if not kpi_base_dir.exists():
        print(f"KPI directory not found: {kpi_base_dir}")
        return

    for run_dir in kpi_base_dir.iterdir():
        if run_dir.is_dir():
            run_id = run_dir.name
            available_runs.append(run_id)
            available_kpis[run_id] = []

            for kpi_file in run_dir.glob("*.csv"):
                file_name = kpi_file.stem
                metadata = KPI_METADATA.get(file_name, {'title': file_name.replace("_", " ").title(), 'unit': ''})
                title = metadata['title']
                unit = metadata.get('unit', '')
                available_kpis[run_id].append({'name': title, 'path': file_name, 'unit': unit})

    output_data = {
        'runs': sorted(available_runs, reverse=True),
        'kpis': available_kpis
    }

    with open(output_data_file, 'w') as f:
        json.dump(output_data, f, indent=4)

    print(f"\nAvailable data generated successfully in {output_data_file}")

if __name__ == '__main__':
    generate_available_data()