import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
import json
import config

KPI_METADATA = {
    'grid_consumption': {
        'title': 'Grid Consumption',
        'description': 'Electricity consumed from the grid by each building over time (in kWh). Negative values indicate electricity exported to the grid.'
    },
    'total_grid_consumption': {
        'title': 'Total Grid Consumption',
        'description': 'Total electricity consumed from the grid by all buildings combined (in kWh).'
    },
    'load': {
        'title': 'Building Load',
        'description': 'Non-shiftable electrical load for each building (in kWh).'
    },
    'total_load': {
        'title': 'Total Building Load',
        'description': 'Total non-shiftable electrical load for all buildings combined (in kWh).'
    },
    'cost': {
        'title': 'Electricity Cost',
        'description': 'The cost of electricity for each building, calculated from grid consumption and electricity price (in $).'
    },
    'total_cost': {
        'title': 'Total Electricity Cost',
        'description': 'The total cost of electricity for all buildings combined (in $).'
    },
    'pv_generation': {
        'title': 'PV Generation',
        'description': 'Electricity generated by photovoltaic (PV) panels for each building (in kWh).'
    },
    'total_pv_generation': {
        'title': 'Total PV Generation',
        'description': 'Total electricity generated by photovoltaic (PV) panels for all buildings combined (in kWh).'
    },
    'electrical_storage_soc': {
        'title': 'Electrical Storage SoC',
        'description': 'State of Charge (SoC) of the electrical storage (battery) for each building (as a percentage).'
    },
    'total_electrical_storage_soc': {
        'title': 'Total Electrical Storage SoC',
        'description': 'This plot is not particularly meaningful as it sums the SoC percentages of different batteries.'
    },
    'electrical_storage_action': {
        'title': 'Electrical Storage Action',
        'description': 'Action taken by the agent for the electrical storage of each building. Positive values indicate charging, negative values indicate discharging.'
    },
    'total_electrical_storage_action': {
        'title': 'Total Electrical Storage Action',
        'description': 'Sum of all electrical storage actions across all buildings.'
    },
    'summary_kpis': {
        'title': 'Summary KPIs',
        'description': 'A summary of key performance indicators for the entire simulation run.'
    }
}

def generate_plots():
    """
    Scans for simulation runs, generates interactive plots for all KPIs,
    and creates a dynamic index.html file to view and compare them.
    """
    kpi_base_dir = Path(config.KPI_OUTPUT_DIR)
    output_plot_dir = Path('gui/plots')
    output_plot_dir.mkdir(exist_ok=True)

    available_runs = []
    available_kpis = {}

    if not kpi_base_dir.exists():
        print(f"KPI directory not found: {kpi_base_dir}")
        return

    # --- 1. Scan for runs and generate plots ---
    for run_dir in kpi_base_dir.iterdir():
        if run_dir.is_dir():
            run_id = run_dir.name
            available_runs.append(run_id)
            available_kpis[run_id] = []
            
            run_plot_dir = output_plot_dir / run_id
            run_plot_dir.mkdir(exist_ok=True)

            for kpi_file in run_dir.glob("*.csv"):
                df = pd.read_csv(kpi_file)
                file_name = kpi_file.stem
                plot_file_name = f'{file_name}.html'

                metadata = KPI_METADATA.get(file_name, {'title': file_name.replace("_", " ").title(), 'description': ''})
                title = metadata['title']
                description = metadata['description']

                fig = None
                if file_name == 'summary_kpis':
                    fig = go.Figure(data=[go.Table(
                        header=dict(values=list(df.columns), fill_color='#d2b48c', align='left'),
                        cells=dict(values=[df[col] for col in df.columns], fill_color='#e8e4c9', align='left'))
                    ])
                elif 'timestamp' in df.columns:
                    fig = px.line(df, x='timestamp', y=df.columns[1:])
                
                if fig:
                    fig.update_layout(
                        title_text=f"<b>{title}</b><br><sub>{description}</sub>",
                        plot_bgcolor='white',
                        paper_bgcolor='white',
                        font_color='black',
                        legend_title_text='Buildings',
                        margin=dict(l=40, r=40, t=80, b=40) # Adjust margins
                    )
                    
                    # Generate a minimal HTML file for the plot
                    fig.write_html(run_plot_dir / plot_file_name, full_html=False, include_plotlyjs='cdn')

                    available_kpis[run_id].append({'name': title, 'path': plot_file_name})
                else:
                    print(f"Skipping {kpi_file} as it could not be plotted.")
    
    # --- 2. Create the main index.html ---
    try:
        with open('gui/index.template.html', 'r') as f:
            template = f.read()
    except FileNotFoundError:
        print("Could not find gui/index.template.html template. Please ensure it exists.")
        return

    # Inject the dynamic data into the template
    js_available_runs = json.dumps(sorted(available_runs, reverse=True))
    js_available_kpis = json.dumps(available_kpis)
    
    final_html = template.replace(
        'const availableRuns = [];',
        f'const availableRuns = {js_available_runs};'
    ).replace(
        'const availableKPIs = {};',
        f'const availableKPIs = {js_available_kpis};'
    )

    with open('gui/index.html', 'w') as f:
        f.write(final_html)

    print("\nPlots generated successfully in the 'gui/plots' directory.")
    print("Open 'gui/index.html' in your browser to view the dashboard.")

if __name__ == '__main__':
    generate_plots()